import{firebaseConfig}from"./firebase-config.js";import{initializeApp}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";import{getFirestore,doc,setDoc,updateDoc,deleteDoc,collection,onSnapshot,serverTimestamp,Timestamp}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";
const db=getFirestore(initializeApp(firebaseConfig)),$=s=>document.querySelector(s),IH="f96771da6ff95d114e7389bc1cd1ee3f9e529f9f382879e25eb19b3366c8bbbc",PH="a689f7b77e734dd1b89911d2ba3c7b23f9c0c6f9d16a517301507829061d55e0";
const hash=async t=>[...new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(t)))].map(b=>b.toString(16).padStart(2,"0")).join("");
$("#adminLogin").onclick=async()=>{if(await hash($("#adminId").value)!==IH||await hash($("#adminPw").value)!==PH){$("#loginMsg").classList.remove("hidden");return $("#loginMsg").textContent="로그인 정보가 올바르지 않습니다."}sessionStorage.setItem("adm","1");open()};
$("#logout").onclick=()=>{sessionStorage.removeItem("adm");location.reload()};
function open(){$("#login").classList.add("hidden");$("#app").classList.remove("hidden");listen()}
function listen(){onSnapshot(collection(db,"members"),s=>{let f=$("#memberFilter").value,a=s.docs.map(d=>({id:d.id,...d.data()})).filter(x=>f==="all"||x.status===f);$("#members").innerHTML=a.length?a.map(x=>`<div class="item"><b>${x.name}</b><div class="muted">${x.memberId} · ${x.email||"-"} · ${(x.role||"member")==="subscriber"?"구독자":"이용자"}</div><span class="badge">${x.status}</span>${x.approvalSongTitle?`<div class="notice">승인 음악: ${x.approvalSongTitle}</div>`:""}<div class="actions"><button class="ok" onclick="approveMember('${x.id}')">승인 + 음악 제목</button><button class="no" onclick="ms('${x.id}','rejected')">거절</button><button class="secondary" onclick="mr('${x.id}','member')">이용자</button><button class="secondary" onclick="mr('${x.id}','subscriber')">구독자</button><button class="delete" onclick="md('${x.id}')">삭제</button></div></div>`).join(""):'<div class="empty">회원 없음</div>'});
onSnapshot(collection(db,"requests"),s=>{let a=s.docs.map(d=>({id:d.id,...d.data()}));$("#requests").innerHTML=a.length?a.map(x=>`<div class="item"><b>${x.requestMode==="lyrics"?"가사 키워드 신청":x.song}</b><div class="muted">${x.artist||"제목·가수 미입력"} · ${x.genre} · ${x.name}</div><div class="notice">${(x.lyricsKeywords||[]).join(", ")}</div><span class="badge">${x.status}</span><div class="actions"><button class="ok" onclick="rs('${x.id}','approved')">승인</button><button class="no" onclick="rs('${x.id}','rejected')">거절</button><button class="delete" onclick="rd('${x.id}')">🗑 삭제</button></div></div>`).join(""):'<div class="empty">신청 없음</div>'});
onSnapshot(doc(db,"settings","schedule"),s=>{if(s.exists())$("#schedule").textContent=s.data().start.toDate().toLocaleString()+" ~ "+s.data().end.toDate().toLocaleString()})}
window.approveMember=async i=>{const title=prompt("회원 승인과 함께 이용자에게 표시할 음악 제목을 입력하세요.");if(title===null)return;const songTitle=title.trim();if(!songTitle)return alert("음악 제목을 입력해야 승인할 수 있습니다.");await updateDoc(doc(db,"members",i),{status:"approved",approvalSongTitle:songTitle,approvalNotice:`회원 승인이 완료되었습니다. 관리자가 설정한 음악: ${songTitle}`,approvalNoticeUnread:true,reviewedAt:serverTimestamp(),approvalNoticeAt:serverTimestamp()});alert("회원 승인 및 이용자 알림 등록이 완료되었습니다.")};
window.ms=(i,s)=>updateDoc(doc(db,"members",i),{status:s,reviewedAt:serverTimestamp()});window.mr=(i,r)=>updateDoc(doc(db,"members",i),{role:r,updatedAt:serverTimestamp()});window.md=i=>deleteDoc(doc(db,"members",i));window.rs=(i,s)=>updateDoc(doc(db,"requests",i),{status:s,notice:s==="approved"?"음원 승인":"음원 거절",updatedAt:serverTimestamp()});window.rd=async i=>{if(!confirm("이 신청곡을 완전히 삭제하시겠습니까?\n삭제 후 복구할 수 없습니다."))return;try{await deleteDoc(doc(db,"requests",i));alert("신청곡이 완전히 삭제되었습니다.")}catch(e){console.error(e);alert("삭제하지 못했습니다.")}};
$("#saveSchedule").onclick=()=>setDoc(doc(db,"settings","schedule"),{start:Timestamp.fromDate(new Date($("#start").value)),end:Timestamp.fromDate(new Date($("#end").value)),updatedAt:serverTimestamp()});$("#memberFilter").onchange=()=>location.reload();if(sessionStorage.getItem("adm")==="1")open();
